---

- name: install essential tools for install docker
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common, gnupg, lsb-release]
  become: yes

- name: Create directory
  file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes

- name: register GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  become: yes

- name: check permission of GPG
  shell: "chmod a+r /etc/apt/keyrings/docker.gpg"
  become: yes

- name: Install packages
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: yes

- name: Install docker CE and containerd
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
    update_cache: yes
  become: yes
