---

# 必要そうなコマンド一式をインストールする
- name: install essential packages from base repository
  apt: name={{item}} state=latest
  with_items:
    - wget
    - lsof
    - man
    - tree
    - dstat
    - vim
    - zsh
    - openssl
    - git
    - tmux
    - htop
    - tig

- name: guest machine goes to reboot
  local_action: wait_for port=2222 state=Stopped

- name: guest machine goest to up
  local_action: wait_for port=2222 delay=30
