---

# 必要そうなコマンド一式をインストールする
- name: install essential packages from base repository
  apt: name={{item}} state=latest
  with_items:
    - wget
    - lsof
    - man
    - tree
    - dstat
    - vim
    - zsh
    - openssl
    - git
    - tmux
    - htop
    - tig


- name: execute reboot
  shell: "sudo reboot"
  async: 1
  pool: 0

- name: wait for the guest goes to down
  local_action: wait_for port=2222 state=stopped
