---

# 必要そうなコマンド一式をインストールする
- name: install essential packages from base repository
  apt: name={{item}} state=latest
  with_items:
    - wget
    - lsof
    - man
    - tree
    - dstat
    - vim
    - zsh
    - openssl
    - git
    - tmux
    - htop
    - tig

