---

- name: Preparate install .rbenv and ruby-build
  apt: name={{item}} state=present
  with_items:
    - git
    - curl
    - g++
    - make
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - sqlite3
    - libsqlite3-dev
  become: yes

- name: Clone rbenv into local
  git:
    repo: git://github.com/sstephenson/rbenv.git
    dest: /home/vagrant/.rbenv
    accept_hostkey: yes

- name: Change .rbenv folder owner from root to vagrant
  file:
    dest: /home/vagrant/.rbenv
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Clone ruby-build into local
  git:
    repo: git://github.com/sstephenson/ruby-build.git
    dest: /home/vagrant/.rbenv/plugins/ruby-build
    accept_hostkey: yes

- name: Change ruby-build folder owner from root to vagrant
  file:
    dest: /home/vagrant/.rbenv/plugins/ruby-build
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Update bashrc to able to load .rbenv and ruby-build
  shell: >
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/vagrant/.bashrc && echo 'eval "$(rbenv init -)"' >> /home/vagrant/.bashrc && exec $SHEL
  args:
    creates: /var/lib/ansible/updated-bashrc-rbenv-and-ruby-build

- name: Touch flagfile of previous task
  file:
    path: /var/lib/ansible/updated-bashrc-rbenv-and-ruby-build
    state: touch
    group: vagrant
    owner: vagrant
    mode: 0400
  become: yes

- name: Install library feedparser
  pip:
    name: feedparser
    state: present

- name: Deploy the script which checks latest version of ruby
  copy:
    src: usr/local/bin/check_latest_version_of_ruby
    dest: /usr/local/bin/check_latest_version_of_ruby
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Check latest version of ruby
  shell: /usr/local/bin/check_latest_version_of_ruby
  register: latest_ruby_version

- name: Install latest version ruby
  shell: /home/vagrant/.rbenv/bin/rbenv install {{ latest_ruby_version.stdout }}
