---

- name: copy ssh keys from host to guest
  copy:
    src: ~/.ssh/{{item}}
    dest: /home/vagrant/.ssh/{{item}}
    owner: vagrant
    group: vagrant
    mode: 0400
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Make ansible working directory
  file:
    path: /var/lib/ansible
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755
  become: yes

######################
# Install lazydocker
######################
- name: Download installer
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: /usr/local/src/install_update_linux.sh
    mode: 0755

- name: execute install script
  shell: bash /usr/local/src/install_update_linux.sh
  become: yes
