---

- name: copy ssh keys from host to guest
  copy:
    src: ~/.ssh/{{item}}
    dest: /home/vagrant/.ssh/{{item}}
    owner: vagrant
    group: vagrant
    mode: 0400
  ignore_errors: yes
  with_items:
    - id_rsa
    - id_rsa.pub
    - id_ed25519
    - id_ed25519.pub

- name: Make ansible working directory
  file:
    path: /var/lib/ansible
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755
  become: yes

######################
# Install h2load
######################
- name: Install essential package to build h2load
  apt:
    name: ['g++', 'make', 'binutils', 'autoconf', 'automake', 'autotools-dev', 'libtool', 'pkg-config', 'zlib1g-dev', 'libcunit1-dev', 'libssl-dev', 'libxml2-dev', 'libev-dev', 'libevent-dev', 'libjansson-dev', 'libc-ares-dev', 'libjemalloc-dev', 'cython', 'python3-dev', 'python-setuptools', 'libjemalloc-dev', 'libspdylay-dev']
    state: latest
  become: yes

- name: Clone nghttp2
  git:
    repo: https://github.com/nghttp2/nghttp2.git
    dest: /home/vagrant/nghttp2
    accept_hostkey: yes
  ignore_errors: true

- name: Build nghttp2
  shell: >
    cd /home/vagrant/nghttp2 && autoreconf -i && automake && autoconf && ./configure --enable-app && make
  args:
    creates: /var/lib/ansible/nghttp2-build

- name: Touch flagfile of previous task
  file:
    path: /var/lib/ansible/nghttp2-build
    state: touch
    group: vagrant
    owner: vagrant
    mode: 0400
  become: yes

######################
# Install lazydocker
######################
- name: Download installer
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: /usr/local/src/install_update_linux.sh
    mode: 0755

- name: execute install script
  shell: bash /usr/local/src/install_update_linux.sh
  become: yes
